import { useEffect,useState } from 'react'
import { ArrowRight, BookOpen, Code2, Users } from 'lucide-react'
import { Link, Navigate } from 'react-router-dom'
import { useAuth } from '../features/auth/AuthProvider'
import { supabase } from '../lib/supabase/client'
import type { Course, TeacherFeedback } from '../types/classroom'

export function HomePage(){const{role}=useAuth();return <Navigate to={role==='student'?'/student':'/teacher'} replace/>}
export function StudentDashboard(){const{session}=useAuth();const[courses,setCourses]=useState<Course[]>([]);const[feedback,setFeedback]=useState<TeacherFeedback[]>([]);useEffect(()=>{void(async()=>{const[c,f]=await Promise.all([supabase.from('cs_courses').select('*,cs_enrollments!inner(student_id)').eq('cs_enrollments.student_id',session!.user.id).eq('status','published'),supabase.from('cs_teacher_feedback').select('*,cs_activity_attempts(*,cs_activities(title))').eq('student_id',session!.user.id).order('created_at',{ascending:false}).limit(5)]);setCourses((c.data??[]) as Course[]);setFeedback((f.data??[]) as TeacherFeedback[])})()},[session]);return <main className="page"><p className="eyebrow">YOUR LEARNING</p><h1>Ready to keep building?</h1>{courses[0]?<section className="hero-card"><div><span className="pill">Continue learning</span><h2>{courses[0].title}</h2><p>{courses[0].description}</p><Link className="button link-button" to={`/student/course/${courses[0].id}`}>Open course <ArrowRight size={18}/></Link></div><Code2 size={72}/></section>:<div className="empty"><BookOpen/><h2>No course assigned yet</h2><p>Ask your teacher to enroll you in a published course.</p></div>}<h2>Your courses</h2><div className="course-grid">{courses.map(c=><Link className="course-card" key={c.id} to={`/student/course/${c.id}`}><BookOpen/><h3>{c.title}</h3><p>{c.description}</p><span className="text-link">Continue <ArrowRight size={16}/></span></Link>)}</div>{feedback.length>0&&<section className="feedback-section"><h2>Teacher feedback</h2>{feedback.map(f=><article className="feedback-card" key={f.id}><strong>{f.cs_activity_attempts?.cs_activities?.title??'Recent activity'}</strong><p>{f.comment}</p><span>{new Date(f.created_at).toLocaleDateString()}</span></article>)}</section>}</main>}
export function TeacherDashboard(){const[counts,setCounts]=useState({students:0,courses:0,work:0});useEffect(()=>{void(async()=>{const[s,c,w]=await Promise.all([supabase.from('cs_profiles').select('*',{count:'exact',head:true}).eq('role','student'),supabase.from('cs_courses').select('*',{count:'exact',head:true}),supabase.from('cs_code_workspaces').select('*',{count:'exact',head:true})]);setCounts({students:s.count??0,courses:c.count??0,work:w.count??0})})()},[]);return <main className="page"><p className="eyebrow">CLASS OVERVIEW</p><h1>Your teaching workspace</h1><div className="stat-grid"><article className="stat"><Users/><strong>{counts.students}</strong><span>Students</span></article><article className="stat"><BookOpen/><strong>{counts.courses}</strong><span>Courses</span></article><article className="stat"><Code2/><strong>{counts.work}</strong><span>Saved workspaces</span></article></div><div className="dashboard-actions"><Link className="action-card" to="/teacher/courses"><BookOpen/><div><h2>Build curriculum</h2><p>Create courses, lessons, Python challenges, and manage students.</p></div><ArrowRight/></Link><Link className="action-card" to="/teacher/submissions"><Code2/><div><h2>Review student code</h2><p>Open saved work, track submissions, and leave feedback.</p></div><ArrowRight/></Link></div></main>}
export function Placeholder({title}:{title:string}){return <main className="page"><p className="eyebrow">CS STUDIO</p><h1>{title}</h1></main>}
