import { useEffect,useMemo,useState } from 'react'
import { Link,useParams } from 'react-router-dom'
import CodeMirror from '@uiw/react-codemirror'
import { python } from '@codemirror/lang-python'
import { ArrowLeft,BookOpen,CheckCircle2,Code2,Play,RotateCcw,Save,Send,Terminal } from 'lucide-react'
import { supabase } from '../lib/supabase/client'
import { runPython } from '../lib/pyodide/runner'
import { useAuth } from '../features/auth/AuthProvider'
import type { Activity,Challenge,CodeWorkspace,Course,Lesson,Module,TestCase,TestResult } from '../types/classroom'
import { scorePassedTests } from '../utils/learning'

export function StudentCoursePage(){const{courseId}=useParams();const[course,setCourse]=useState<Course|null>(null);const[modules,setModules]=useState<Module[]>([]);const[lessons,setLessons]=useState<Lesson[]>([]);const[activities,setActivities]=useState<Activity[]>([]);useEffect(()=>{void(async()=>{const[c,m,l,a]=await Promise.all([supabase.from('cs_courses').select('*').eq('id',courseId!).single(),supabase.from('cs_modules').select('*').eq('course_id',courseId!).eq('status','published').order('position'),supabase.from('cs_lessons').select('*,cs_modules!inner(course_id)').eq('cs_modules.course_id',courseId!).eq('status','published').order('position'),supabase.from('cs_activities').select('*,cs_lessons!inner(cs_modules!inner(course_id))').eq('cs_lessons.cs_modules.course_id',courseId!).eq('status','published').order('position')]);setCourse(c.data);setModules(m.data??[]);setLessons((l.data??[]) as unknown as Lesson[]);setActivities((a.data??[]) as unknown as Activity[])})()},[courseId]);return <main className="page"><Link className="back" to="/student"><ArrowLeft size={17}/> Dashboard</Link><p className="eyebrow">YOUR COURSE</p><h1>{course?.title??'Loading…'}</h1><p className="lede">{course?.description}</p><div className="learning-path">{modules.map((m,mi)=><section className="module-block" key={m.id}><div className="module-number">{mi+1}</div><div><h2>{m.title}</h2><p>{m.description}</p>{lessons.filter(l=>l.module_id===m.id).map(l=><article className="lesson-card" key={l.id}><BookOpen/><div><h3>{l.title}</h3><p>{l.introduction}</p><div className="activity-links">{activities.filter(a=>a.lesson_id===l.id).map(a=><Link key={a.id} to={`/student/activity/${a.id}`}><Code2 size={16}/>{a.title}<span>{a.difficulty}</span></Link>)}</div></div></article>)}</div></section>)}</div></main>}

function challengeValue(value:Challenge|Challenge[]|undefined){return Array.isArray(value)?value[0]:value}
export function PythonActivityPage(){
 const{activityId}=useParams();const{session}=useAuth();const[activity,setActivity]=useState<Activity|null>(null);const[code,setCode]=useState('');const[output,setOutput]=useState('Run your program to see output.');const[input,setInput]=useState('');const[loading,setLoading]=useState(false);const[saving,setSaving]=useState(false);const[savedAt,setSavedAt]=useState('');const[workspaceId,setWorkspaceId]=useState('');const[teacherReview,setTeacherReview]=useState('');const[results,setResults]=useState<TestResult[]>([]);const[message,setMessage]=useState('');const challenge=useMemo(()=>challengeValue(activity?.cs_coding_challenges),[activity]);
 useEffect(()=>{void(async()=>{const[{data,error},{data:workspace,error:workspaceError}]=await Promise.all([supabase.from('cs_activities').select('*,cs_coding_challenges(*)').eq('id',activityId!).single(),supabase.from('cs_code_workspaces').select('*,cs_workspace_feedback(*)').eq('activity_id',activityId!).eq('student_id',session!.user.id).maybeSingle()]);if(error||workspaceError){setMessage(error?.message??workspaceError?.message??'Could not load this exercise');return}const value=data as Activity;const coding=challengeValue(value.cs_coding_challenges);if(coding){const{data:tests,error:testError}=await supabase.from('cs_student_test_cases').select('*').eq('challenge_id',activityId!).order('position');if(testError){setMessage(testError.message);return}coding.cs_coding_test_cases=(tests??[]) as TestCase[]}setActivity(value);const saved=workspace as CodeWorkspace|null;const starter=coding?.starter_code??'';setCode(saved?.code??localStorage.getItem(`cs-draft-${activityId}`)??starter);if(saved){setWorkspaceId(saved.id);setSavedAt(saved.updated_at);setTeacherReview(saved.cs_workspace_feedback?.[0]?.comment??'')}})()},[activityId,session])
 useEffect(()=>{if(activityId)localStorage.setItem(`cs-draft-${activityId}`,code)},[code,activityId])
 const saveCode=async(showMessage=true)=>{setSaving(true);const{data,error}=await supabase.from('cs_code_workspaces').upsert({activity_id:activityId,student_id:session!.user.id,code,updated_at:new Date().toISOString()},{onConflict:'activity_id,student_id'}).select('id,updated_at').single();setSaving(false);if(error){setMessage(error.message);return false}setWorkspaceId(data.id);setSavedAt(data.updated_at);if(showMessage)setMessage('Code saved to your class workspace');return true}
 const run=async(runCode=code,stdin=input)=>{setLoading(true);setOutput('Loading Python environment…');const result=await runPython(runCode,stdin);const text=[result.stdout,result.stderr].filter(Boolean).join('\n');setOutput(text||'(Program finished with no output)');setLoading(false);return result}
 const test=async(submit=false)=>{setLoading(true);if(submit&&!(await saveCode(false))){setLoading(false);return}const tests=(challenge?.cs_coding_test_cases??[]) as TestCase[];const outputs:{id:string;output:string}[]=[];for(const t of tests){const r=await runPython(code,t.input);outputs.push({id:t.id,output:r.stderr||r.stdout.trim()})}const{data,error:gradeError}=await supabase.rpc('cs_grade_test_outputs',{target_activity:activityId!,outputs});if(gradeError){setMessage(gradeError.message);setLoading(false);return}const next=(data??[]) as TestResult[];setResults(next);const score=scorePassedTests(next.map(x=>x.passed),Number(activity?.max_score??100));const summary=next.every(x=>x.passed)?'All tests passed. Great work!':'Some tests need another look.';setOutput(summary);if(submit){const{count}=await supabase.from('cs_activity_attempts').select('*',{count:'exact',head:true}).eq('activity_id',activityId!).eq('student_id',session!.user.id);const{error}=await supabase.from('cs_activity_attempts').insert({activity_id:activityId,student_id:session!.user.id,code,stdout:summary,status:next.every(x=>x.passed)?'passed':'failed',score,test_results:next,attempt_number:(count??0)+1});setMessage(error?.message??`Submitted to your teacher · ${score}%`)}setLoading(false)}
 const reset=()=>{setCode(challenge?.starter_code??'');setResults([]);setOutput('Starter code restored.')}
 return <main className="lab-page"><div className="lab-heading"><div><Link className="back" to="/student"><ArrowLeft size={17}/> Dashboard</Link><span className="pill light">{activity?.difficulty??'core'}</span><h1>{activity?.title??'Python challenge'}</h1><p>{activity?.instructions}</p>{savedAt&&<span className="save-state">Saved for your teacher {new Date(savedAt).toLocaleString()}</span>}</div><div className="heading-actions"><button className="button secondary" disabled={loading||saving} onClick={()=>void saveCode()}><Save size={17}/> {saving?'Saving…':'Save code'}</button><button className="button" disabled={loading||saving} onClick={()=>void test(true)}><Send size={17}/> Submit</button></div></div>{message&&<p className="status">{message}</p>}{teacherReview&&<section className="student-review"><strong>Teacher feedback on your saved code</strong><p>{teacherReview}</p></section>}<div className="ide"><section className="editor-pane"><header><Code2 size={17}/> main.py {workspaceId&&<span>Class workspace</span>}</header><CodeMirror value={code} height="420px" extensions={[python()]} onChange={setCode} theme="dark" basicSetup={{lineNumbers:true,foldGutter:false}}/></section><section className="console-pane"><header><Terminal size={17}/> Output</header><pre>{output}</pre><label className="console-input"><span>Program input (one value per line)</span><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Optional input() values"/></label></section></div><div className="lab-actions"><button className="button" disabled={loading} onClick={()=>void run()}><Play size={17}/> {loading?'Running…':'Run code'}</button><button className="button secondary" disabled={loading} onClick={()=>void test()}><CheckCircle2 size={17}/> Test my code</button><button className="button ghost" onClick={reset}><RotateCcw size={17}/> Reset</button></div>{results.length>0&&<section className="test-panel"><h2>Test results</h2>{results.map(r=><div className={r.passed?'test passed':'test failed'} key={r.name}><strong>{r.passed?'✓':'✗'} {r.name}: {r.passed?'Passed':'Failed'}</strong>{!r.passed&&r.expected!==undefined&&<span>Expected “{r.expected}”, got “{r.actual}”</span>}</div>)}</section>}</main>
}
